name: take_my_tym
description: "A freelance application."

publish_to: "none"

version: 2.2.0+5

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  logger: ^2.2.0
  flutter_screenutil: ^5.9.0
  get_it: ^7.6.7
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  image_picker: ^1.0.7
  permission_handler:
  back_button_interceptor: ^5.0.2
  url_launcher: ^6.2.5
  path_provider: ^2.1.2
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  vibration: ^1.8.4
  audioplayers: ^6.0.0
  local_auth: ^2.2.0
  share_plus: ^9.0.0
  flutter_local_notifications: ^17.1.2
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  http: ^1.2.1
  flutter_phoenix: ^1.1.1

  hive: ^2.2.3
  firebase_auth: ^4.17.8
  firebase_core: ^2.26.0
  cloud_firestore: ^4.15.10
  google_sign_in: ^6.2.1
  firebase_storage: ^11.7.0
  firebase_analytics: ^10.10.5
  flutter_stripe: ^10.1.1
  firebase_messaging: ^14.9.3

  flutter_svg: ^2.0.10+1
  animate_do: ^3.3.4
  iconly: ^1.0.1
  lottie: ^3.1.0
  animated_toggle_switch: ^0.8.2
  shimmer_pro: ^0.0.6
  button_animations: ^2.0.0+3
  timeline_tile: ^2.0.0
  dotlottie_loader: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/lottie/
    - assets/audio/
    - assets/svg/
    - assets/svg/snackbar/
    - assets/svg/icons/
    - assets/png/
    - assets/png/ad/
    - assets/png/auth/
    - assets/png/icon/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/font/gilroy/Gilroy-Medium.ttf
        - asset: assets/font/gilroy/Gilroy-UltraLight.ttf
          weight: 100
        - asset: assets/font/gilroy/Gilroy-Thin.ttf
          weight: 200
        - asset: assets/font/gilroy/Gilroy-Light.ttf
          weight: 300
        - asset: assets/font/gilroy/Gilroy-Light.ttf
          weight: 400
        - asset: assets/font/gilroy/Gilroy-Regular.ttf
          weight: 500
        - asset: assets/font/gilroy/Gilroy-Medium.ttf
          weight: 600
        - asset: assets/font/gilroy/Gilroy-SemiBold.ttf
          weight: 700
        - asset: assets/font/gilroy/Gilroy-ExtraBold.ttf
          weight: 800
        - asset: assets/font/gilroy/Gilroy-Heavy.ttf
          weight: 900

    # - family: Poppins
    #   fonts:
    #     - asset: assets/font/Poppins/Poppins-Regular.ttf
    #     - asset: assets/font/Poppins/Poppins-Medium.ttf
    #       weight: 500
    #     - asset: assets/font/Poppins/Poppins-SemiBold.ttf
    #       weight: 600
    #     - asset: assets/font/Poppins/Poppins-Bold.ttf
    #       weight: 700
    #     - asset: assets/font/Poppins/Poppins-ExtraBold.ttf
    #       weight: 800
    #     - asset: assets/font/Poppins/Poppins-Black.ttf
    #       weight: 900
